# -*- coding: utf-8 -*-
"""lct.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqjHlvJbd6d0e7Yd3aEMDwiI5khsfJSG

Carga del archivo txt
"""

from google.colab import files

uploaded = files.upload()

with open("ley-contrato-trabajo.txt", "r", encoding="utf-8") as f:
    texto = f.read()

print(texto[:2000])  # muestra los primeros caracteres

print("Caracteres:", len(texto))
print("Palabras:", len(texto.split()))
print("Líneas:", len(texto.splitlines())) # para conocer el alcance del documento

"""Limpieza del documento"""

import re

def limpiar_texto(texto):

    # Eliminar sección Antecedentes Normativos
    texto = re.sub(
        r'Antecedentes Normativos.*$',
        '',
        texto,
        flags=re.DOTALL | re.IGNORECASE
    )

    # Eliminar anotaciones editoriales
    patrones = [
        r'\(Nota Infoleg.*?\)',
        r'\(Capítulo.*?\)',
        r'\(Artículo.*?\)',
        r'\(Inciso.*?\)',
        r'\(Párrafo.*?\)',
        r'\(Denominación.*?\)'
    ]

    for patron in patrones:
        texto = re.sub(
            patron,
            '',
            texto,
            flags=re.DOTALL | re.IGNORECASE
        )

    # Normalizar espacios
    texto = re.sub(r'[ \t]+', ' ', texto)

    # Normalizar saltos de línea
    texto = re.sub(r'\n{3,}', '\n\n', texto)

    return texto.strip()

texto_limpio = limpiar_texto(texto)

print("Palabras antes:", len(texto.split()))
print("Palabras después:", len(texto_limpio.split()))

# Validación

print("Antecedentes Normativos" in texto_limpio)
print("(Nota Infoleg" in texto_limpio)
print("(Artículo" in texto_limpio)
print("(Capítulo" in texto_limpio)

"""Exploración de la estructura del documento en títulos y capítulos"""

import re

titulos = re.findall(
    r'^TITULO\s+[IVXLCDM]+.*?$',
    texto_limpio,
    flags=re.MULTILINE
)

print(f"Títulos encontrados: {len(titulos)}")

for t in titulos:
    print(t)

import re

capitulos = re.findall(
    r'^CAPITULO\s+[IVXLCDM]+.*?$',
    texto_limpio,
    flags=re.MULTILINE
)

print(f"Capítulos encontrados: {len(capitulos)}")

for c in capitulos[:20]:
    print(c)

inicio = texto_limpio.find("TITULO II")

print(texto_limpio[inicio:inicio+1000])

lineas = texto_limpio.splitlines()

for i, linea in enumerate(lineas[:50]):
    print(i, repr(linea))

"""Limpieza luego de la exploración de estructura"""

texto_limpio = texto_limpio.replace('\ufeff', '')
lineas = [l.strip() for l in texto_limpio.splitlines()]

# eliminar líneas vacías
lineas = [l for l in lineas if l]

print(lineas[:20])

"""Construcción de secciones:"""

secciones = []

current_title = None
current_title_name = None

current_chapter = None
current_chapter_name = None

buffer = []

def guardar_seccion():

    global buffer, secciones
    global current_title, current_title_name
    global current_chapter, current_chapter_name

    if not buffer:
        return

    secciones.append({
        "titulo": current_title,
        "titulo_nombre": current_title_name,
        "capitulo": current_chapter,
        "capitulo_nombre": current_chapter_name,
        "texto": " ".join(buffer).strip()
    })

    buffer = []

for linea in lineas:

    linea = linea.strip()

    if not linea:
        continue

    # TITULO
    if re.match(r'^TITULO\s+[IVXLCDM]+$', linea):

        guardar_seccion()

        current_title = linea
        current_title_name = None

        current_chapter = None
        current_chapter_name = None

        continue

    # nombre del título
    if (
        current_title
        and current_title_name is None
        and not re.match(r'^CAPITULO|^Art|^Artículo', linea)
    ):
        current_title_name = linea
        continue

    # CAPITULO
    if re.match(r'^CAPITULO\s+[IVXLCDM]+$', linea):

        guardar_seccion()

        current_chapter = linea
        current_chapter_name = None

        continue

    # nombre del capítulo
    if (
        current_chapter
        and current_chapter_name is None
        and not re.match(r'^CAPITULO|^Art|^Artículo', linea)
    ):
        current_chapter_name = linea
        continue

    # contenido
    buffer.append(linea)

# guardar última sección
guardar_seccion()

secciones = secciones[1:] # limpieza de secciones

for i, sec in enumerate(secciones):

    palabras = len(sec["texto"].split())

    print(
        f"{i:02d} | "
        f"{sec['titulo']} | "
        f"{sec['capitulo']} | "
        f"{palabras} palabras"
    )

"""Chunking
Reglas:
1. Respetar estructura jurídica de divisón por títulos y capítulos, por lo que el corte se realizaría en primer lugar por títulos y capítulos.
2. Cuando el capítulo supere las 800 palabras, realizaremos el corte en 800 palabras con overlap de 50 palabras.


"""

MAX_WORDS = 800
OVERLAP = 50

chunks_finales = []

for seccion in secciones:

    palabras = seccion["texto"].split()

    # Caso 1: la sección entra completa
    if len(palabras) <= MAX_WORDS:

        chunks_finales.append({
            "titulo": seccion["titulo"],
            "titulo_nombre": seccion["titulo_nombre"],
            "capitulo": seccion["capitulo"],
            "capitulo_nombre": seccion["capitulo_nombre"],
            "chunk_id": 1,
            "texto": seccion["texto"],
            "word_count": len(palabras)
        })

    # Caso 2: hay que dividir
    else:

        inicio = 0
        chunk_id = 1

        while inicio < len(palabras):

            fin = min(inicio + MAX_WORDS, len(palabras))

            chunk_words = palabras[inicio:fin]

            chunks_finales.append({
                "titulo": seccion["titulo"],
                "titulo_nombre": seccion["titulo_nombre"],
                "capitulo": seccion["capitulo"],
                "capitulo_nombre": seccion["capitulo_nombre"],
                "chunk_id": chunk_id,
                "texto": " ".join(chunk_words),
                "word_count": len(chunk_words)
            })

            if fin >= len(palabras):
                break

            inicio = fin - OVERLAP
            chunk_id += 1

"""Cantidad de chunks generados:"""

print("Secciones originales:", len(secciones))
print("Chunks finales:", len(chunks_finales))

"""Ejemplos de fragmentos:"""

for i in range(5):

    c = chunks_finales[i]

    print("\n" + "="*80)
    print("CHUNK", i)

    print("Título:", c["titulo"])
    print("Capítulo:", c["capitulo"])
    print("Chunk ID:", c["chunk_id"])
    print("Palabras:", c["word_count"])

    print("\nInicio:")
    print(c["texto"][:300])

"""DataFrame"""

import pandas as pd

df_chunks = pd.DataFrame(chunks_finales)

df_chunks.head(12)

"""Generación de embeddings:"""

!pip install -q sentence-transformers

from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

textos = [
    chunk["texto"]
    for chunk in chunks_finales
]

print("Cantidad de chunks:", len(textos))

embeddings = model.encode(
    textos,
    convert_to_numpy=True,
    show_progress_bar=True
)

print("Shape:", embeddings.shape)

"""Inspeccionar un embedding:"""

print(embeddings[0][:10])

"""Creación del índice vectorial con FAISS para poder hacer búsquedas semánticas sobre la ley:"""

!pip install -q faiss-cpu
import faiss
import numpy as np

# Normalización de embeddings

faiss.normalize_L2(embeddings)

# Creación del índice

dimension = embeddings.shape[1]

index = faiss.IndexFlatIP(dimension)

# Agrega embeddings al índice

index.add(embeddings)

"""Creación de función de búsqueda:"""

def buscar(query, top_k=5):

    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    faiss.normalize_L2(query_embedding)

    scores, indices = index.search(
        query_embedding,
        top_k
    )

    return scores[0], indices[0]

"""Consulta de prueba:"""

scores, indices = buscar(
    "¿Qué es un trabajador?"
)

for rank, (score, idx) in enumerate(zip(scores, indices), start=1):

    chunk = chunks_finales[idx]

    print("=" * 80)
    print(f"TOP {rank}")
    print(f"Score: {score:.4f}")
    print(f"Título: {chunk['titulo']}")
    print(f"Capítulo: {chunk['capitulo']}")
    print()

    print(chunk["texto"][:500])
    print()

"""Implementación de BM25 para realizar keyword search:"""

!pip install -q rank-bm25
from rank_bm25 import BM25Okapi

# Tokenización de los chunks

tokenized_chunks = [
    chunk["texto"].lower().split()
    for chunk in chunks_finales
]

# Construcción de índice BM25

bm25 = BM25Okapi(tokenized_chunks)

"""Creación de función de búsqueda:"""

def buscar_bm25(query, top_k=5):

    query_tokens = query.lower().split()

    scores = bm25.get_scores(query_tokens)

    if scores.max() == 0:
        print("No se encontraron coincidencias.")
        return None, None

    indices = scores.argsort()[::-1][:top_k]

    return scores, indices

"""Consulta de prueba:"""

scores, indices = buscar_bm25(
    "Trabajador"
)

for rank, idx in enumerate(indices, start=1):

    chunk = chunks_finales[idx]

    print("=" * 80)
    print(f"TOP {rank}")
    print(f"Score BM25: {scores[idx]:.4f}")
    print(f"Título: {chunk['titulo']}")
    print(f"Capítulo: {chunk['capitulo']}")
    print()

    print(chunk["texto"][:500])
    print()

"""Aplicación de Hybrid Search con Reciprocal Rank Fusion (RRF), para combinar los resultados anteriores:"""

def hybrid_search(query, top_k=10, k_rrf=60):

    # ==========================
    # FAISS
    # ==========================

    faiss_scores, faiss_indices = buscar(
        query,
        top_k=top_k
    )

    # ==========================
    # BM25
    # ==========================

    bm25_scores, bm25_indices = buscar_bm25(
        query,
        top_k=top_k
    )

    # ==========================
    # Reciprocal Rank Fusion
    # ==========================

    fusion_scores = {}

    # Ranking FAISS
    for rank, idx in enumerate(faiss_indices):

        fusion_scores[idx] = (
            fusion_scores.get(idx, 0)
            + 1 / (k_rrf + rank + 1)
        )

    # Ranking BM25
    for rank, idx in enumerate(bm25_indices):

        fusion_scores[idx] = (
            fusion_scores.get(idx, 0)
            + 1 / (k_rrf + rank + 1)
        )

    # ==========================
    # Ordenar ranking final
    # ==========================

    ranking_final = sorted(
        fusion_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    return ranking_final

"""Resultados:"""

def mostrar_hybrid(query, top_n=5):

    resultados = hybrid_search(
        query,
        top_k=10
    )

    for pos, (idx, score) in enumerate(
        resultados[:top_n],
        start=1
    ):

        chunk = chunks_finales[idx]

        print("=" * 100)

        print(
            f"TOP {pos}"
        )

        print(
            f"Score híbrido: {score:.4f}"
        )

        print(
            f"Título: {chunk['titulo']}"
        )

        print(
            f"Capítulo: {chunk['capitulo']}"
        )

        print()

        print(
            chunk["texto"][:600]
        )

        print()

"""Prueba de consulta:"""

mostrar_hybrid(
    "trabajador"
)

"""Re-ranking con CrossEncoder:"""

!pip install -q sentence-transformers

from sentence_transformers import CrossEncoder

reranker = CrossEncoder(
    "cross-encoder/ms-marco-MiniLM-L-6-v2"
)

def rerank(query, top_k_hybrid=10):

    resultados = hybrid_search(
        query,
        top_k=top_k_hybrid
    )

    pares = []

    for idx, _ in resultados:

        texto = chunks_finales[idx]["texto"]

        pares.append(
            (query, texto)
        )

    scores = reranker.predict(
        pares
    )

    reranked = []

    for (idx, _), score in zip(
        resultados,
        scores
    ):

        reranked.append(
            (idx, float(score))
        )

    reranked.sort(
        key=lambda x: x[1],
        reverse=True
    )

    return reranked

"""Resultado:"""

def mostrar_reranking(
    query,
    top_n=5
):

    resultados = rerank(query)

    for pos, (idx, score) in enumerate(
        resultados[:top_n],
        start=1
    ):

        chunk = chunks_finales[idx]

        print("=" * 100)

        print(
            f"TOP {pos}"
        )

        print(
            f"Score CrossEncoder: {score:.4f}"
        )

        print(
            f"Título: {chunk['titulo']}"
        )

        print(
            f"Capítulo: {chunk['capitulo']}"
        )

        print()

        print(
            chunk["texto"][:700]
        )

        print()

"""Consulta de prueba:"""

mostrar_reranking(
    "¿Qué es un trabajador?"
)